var products=[
    {
        id:9876,
        name:"Pure Honey",
        cost:950,
        img:"/images/honey.jpg",
        category:"fruits"
    },
    {
        id:48597,
        name:"Desi Ghee",
        cost:654,
        img:"/images/ghee.jpg",
        category:"fruits"
    },
    {
        id:987,
        name:"Cereals",
        cost:754,
        img:"/images/grains.jpg",
        category:"grains"
    },
    {
        id:657,
        name:"Apple",
        cost:30,
        img:"/images/apple.jpg",
        category:"fruits"
    },
    {
        id:9883,
        name:"Banana",
        cost:50,
        img:"/images/banana.jpg",
        category:"fruits"
    },
    {
        id:45698,
        name:"Pomegranate",
        cost:60,
        img:"/images/pomegranate.jpg",
        category:"fruits"
    },
    {
        id:9046,
        name:"Orange",
        cost:754,
        img:"/images/orange.jpg",
        category:"fruits"
    },
    {
        id:2348,
        name:"Popaya",
        cost:754,
        img:"/images/popaya.jpg",
        category:"fruits"
    },
    {
        id:5638,
        name:"Bengal Grams",
        cost:754,
        img:"/images/bengGrams.jpg",
        category:"grains"
    },
    {
        id:26579,
        name:"Fish",
        cost:754,
        img:"/images/fish.jpeg",
        category:"fruits"
    },
    {
        id:25414,
        name:"Brocoli",
        cost:75,
        img:"/images/brocoli.jpg",
        category:"vegetables"
    },
    {
        id:8525,
        name:"Corn",
        cost:22,
        img:"/images/corn.jpeg",
        category:"fruits"
    }
];

module.exports=products;